services:
  - type: web
    name: tau-phah-ji-command
    env: python
    buildCommand: "pip install -r server/requirements.txt"
    startCommand: "python server/app.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
