services:
  - type: web
    name: tau-phah-ji-command-client
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    rootDir: server # 指向包含 package.json 的資料夾

  - type: web
    name: tau-phah-ji-command-server
    env: python
    buildCommand: "pip install -r server/requirements.txt"
    startCommand: "python server/app.py"
    plan: free
